### PR TITLE
Fix nova install

### PR DESCRIPTION
**Pull request by dmason30**
It appears when you merged in the master build passed but it failed to install nova and therefore didn't run those tests hopefully this fixes it although you might just want to do some trial and error on master instead of merging this PR.

### CODE REVIEW

**Comment by mikebronner** [comment]
Not sure if this was necessary, since the builds are passing? Probably doesn't hurt, thought.

**Comment by dmason30** [comment]
@mikebronner Its still not working in master see nova is not installing:
https://travis-ci.org/github/GeneaLabs/laravel-model-caching/jobs/679088787#L445

**Comment by mikebronner** [comment]
Actually, it is downloading. Look at line 448. There must be another reason why Nova tests aren't running?

**Comment by dmason30** [comment]
Just noticed I accidentally left in not sure why it would cause this though:
https://github.com/GeneaLabs/laravel-model-caching/blob/master/phpunit.xml.dist#L15

**Comment by mikebronner** [comment]
Doh! Forgot about php-unit.xml.dist -- thanks for finding that!

**Pull request merged**
