### PR TITLE
Laravel 5.7 support

### PR DESCRIPTION
**Pull request by drbyte**

### CODE REVIEW

**Comment by robtesch** [comment]
Any word on this?

**Comment by mikebronner** [comment]
Sorry, I'm unavailable for a while due to family emergency. Will take a look at everything once I get back.

**Comment by drbyte** [comment]
@mikebronner it's possible you might want to update the `orchestra` dependencies to `3.7.*` as well. The tests "currently" pass without it, but not if versions are strictly matched.

**Comment by mikebronner** [comment]
@drbyte I'm working on that right now, as well as updating tests.

**Pull request merged**
