### PR TITLE
Add unit test for raw clause parsing

### PR DESCRIPTION
**Pull request by hanneskaeufler**
This was a bit of fiddling but this exercises the currently uncovered branch as seen here: https://coveralls.io/builds/13692274/source?filename=src%2FCachedBuilder.php#L93

Fixes issue #17

### CODE REVIEW

**Comment by hanneskaeufler** [comment]
Scrutinizer failure looked unrelated, so I force pushed to retrigger.

**Comment by mikebronner** [comment]
@hanneskaeufler Woohoo! :) Thanks for working on this :) It appears the unit tests are failing. Yea, I restarted Scrutinizer, and it passed. Will wait for them to finish, will then merge. Keep the TDD magic going! :)

**Comment by hanneskaeufler** [comment]
Hehe, my pleasure, love me some testing and I almost got nostalgic about php after a few years of no php work lol 💟

**Comment by mikebronner** [comment]
@hanneskaeufler Make sure you register for Hactoberfest, and if you do the other 3 issues, you will already be eligible for your t-shirt! :)

**Pull request merged**
