### PR TITLE
Fix incorrect cache key in multiple DB connection.

### PR DESCRIPTION
**Pull request by PokeGuys**
This PR fixed a `makeCacheKey` bug mentioned in Issue #212.
It used default DB connection to make query instead of using `$connection` in model.

### CODE REVIEW

**Comment by mikebronner** [comment]
Thanks @PokeGuys ! I will take a look at this as soon as I can. :)

**Comment by PokeGuys** [comment]
This will cause another issue. The eager load relation will be used the caller connection, not their own connection name.

**Comment by mikebronner** [comment]
@PokeGuys thanks for the heads up, I'm close to wrapping up the L5.8 update, and will look at these next.

**Comment by mikebronner** [comment]
@PokeGuys  Thanks for your patience, and bringing this issue up! This will be in the next release. I didn't merge, because there was a bunch of other work that needed to be done to allow model relationships to cache correctly across different connections and databases.

**Pull request closed without merging**
