### PR TITLE
Add pcov coverage & experimental skip nova tests on PRs

### PR DESCRIPTION
**Pull request by dmason30**
I use this in all my projects and tests with coverage run much faster.

### CODE REVIEW

**Comment by mikebronner** [comment]
@dmason30 Any ideas why travis is failing on PR builds, but not on master? I have the environment variables set up in the repo settings, and they build fine on master.

**Comment by dmason30** [comment]
https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

> The most important restriction for pull requests is about secure environment variables and encrypted data.

> A pull request sent from a fork of the upstream repository could be manipulated to expose environment variables. The upstream repository’s maintainer would have no protection against this attack, as pull requests can be sent by anyone who forks the repository on GitHub.

They go on to suggest that tests requiring secure env variables should be skipped on a PR build.

**Comment by mikebronner** [comment]
Thanks for finding that :)

**Comment by dmason30** [comment]
@mikebronner You want me to add exclude nova tests to travis?

**Comment by mikebronner** [comment]
You think you can do that only for PR tests, and not for the main build? If so, that would be great. If not, let's leave it in for now.

**Comment by dmason30** [comment]
Ok so this took a few attempts to get right.

I had to add the `doctrine/dbal` dependency for sqlite support otherwise the tests were erroring on this locally and on travis. 

If you want the pcov without all the nova stuff feel free to reopen and merge https://github.com/GeneaLabs/laravel-model-caching/pull/339

**Comment by mikebronner** [comment]
Awesome, thanks for all the work on this!!!

**Pull request merged**
